name: Update Classes

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  repository_dispatch:
    types: [update_class]


jobs:
  classUpdate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - id: update-src
        uses: refact0r/class-update@v3
        with:
          folder: /
          ext: css
      - uses: EndBug/add-and-commit@v10
        if: ${{steps.update-src.outputs.totalChanges > 0}}
        with:
          default_author: github_actions
          message: "chore: update classes >_<"
          fetch: true
